### PR TITLE
edits

### PR DESCRIPTION
**Pull request by UseMuse**

### CODE REVIEW

**Comment by TarikHuber** [comment]
@UseMuse what did you change in the Layout File?

**Comment by UseMuse** [comment]
@TarikHuber commented out unused

**Comment by TarikHuber** [comment]
arw ypu sure that it's unused? intl is used and we need the pollyfills for IE

**Comment by UseMuse** [comment]
@TarikHuber show me where this is being called. The hook that I commented on contains the function inside and that's it, it is not even called.

**Comment by TarikHuber** [comment]
did you find where it's used?

**Comment by UseMuse** [comment]
@TarikHuber  no) I just returned it all

**Pull request closed without merging**
