### PR TITLE
Fixed a commonstyle bug

### PR DESCRIPTION
**Pull request by Prottoy2938**
Fixed typo on style

### CODE REVIEW

**Comment by TarikHuber** [comment]
1 OK
2 pls leave the prettier as it is. With yours you destroy my style and when I work on the same file I overwrite them anyway. You can see the prettier configs in the package.json file
3 They are ordered alphabetically. In large projects that makes it easyer to find some imports and the order has no effect on how the code works. I have a VS command that orders all import that are selected by pressing CNTRL and F9

Can you pls fix those before I merge. It doesn't make sense to have different prettier cionfigs inside.

**Comment by TarikHuber** [comment]
And pls test your code. Your last PR broke the app and I had to fix some stuff.

**Comment by Prottoy2938** [comment]
Okay, I will. Thanks for the note. I will keep that in mind.

And I don't get why my last PR broke the app? I haven't tested it, but where I made the mistake? I am willing to learn more.

**Comment by TarikHuber** [comment]
It was just a missing import. Not a big deal but as you can see little things can break it. So pls befor every PR just run the project localy to see if it works.

**Comment by Prottoy2938** [comment]
Okay. I think now it's safe to merge. I only fixed a style issue on this updated commit.

**Comment by TarikHuber** [comment]
@Prottoy2938 thx for the PR 😄 sorry it tok so long. A little but corona delay here from germany ;)

**Pull request merged**
