### PR TITLE
Menu state refactor

### PR DESCRIPTION
**Pull request by jswelsh**

### CODE REVIEW

**Comment by UseMuse** [comment]
@jswelsh 
I suggest adding a hook so that it can be reused
```c#

import { useEffect, useRef } from 'react';

export default function useEventListener(eventName, handler, element = window) {
  // Create a ref that stores handler
  const savedHandler = useRef();

  // Update ref.current value if handler changes.
  // This allows our effect below to always get latest handler ...
  // ... without us needing to pass it in effect deps array ...
  // ... and potentially cause effect to re-run every render.
  useEffect(() => {
    savedHandler.current = handler;
  }, [handler]);

  useEffect(
    () => {
      // Make sure element supports addEventListener
      const isSupported = element && element.addEventListener;
      if (!isSupported) return;

      // Create event listener that calls handler function stored in ref
      const eventListener = event => savedHandler.current(event);

      // Add event listener
      element.addEventListener(eventName, eventListener);

      // Remove event listener on cleanup
      return () => {
        element.removeEventListener(eventName, eventListener);
      };
    },
    [eventName, element] // Re-run if eventName or element changes
  );
}
```
example of use
```c#
function App() {
  // State for storing mouse coordinates
  const [coords, setCoords] = useState({ x: 0, y: 0 });

  // Event handler utilizing useCallback ...
  // ... so that reference never changes.
  const handler = useCallback(
    ({ clientX, clientY }) => {
      // Update coordinates
      setCoords({ x: clientX, y: clientY });
    },
    [setCoords]
  );

  // Add event listener using our hook
  useEventListener('mousemove', handler);

  return (
    <h1>
      The mouse position is ({coords.x}, {coords.y})
    </h1>
  );
}
```

**Comment by TarikHuber** [comment]
pls don't change the default behaviour with hardcoded solutions. 
Use for that the config fiel so you can change it in your usecase.

**Comment by jswelsh** [comment]
just to clarify
@UseMuse do you mean `toggleMenuState` function 
```
  const toggleMenuState = (setTo) => {//add
    setDesktopOpen((typeof setTo === "boolean") ? setTo : !isDesktopOpen)
    setMobileOpen((typeof setTo === "boolean") ? setTo : !isMobileOpen)
}
```
refactoring  with a useCallback hook? or am I missing something. If so I'll get that done

@TarikHuber do you specifically mean
1. the default state values that were changed
2. the functions I added that toggle both states together (having both the setDesktopOpen and setMobileOpen to mirror each other)
3. the hook that checks the width and forces  both openstates to toggle closed once a resize occurs less than 600px
4. all

I understand that I've tried to fix #207, so that should be moved out to a config option. But the functions that toggle both open states are to address UX behaviour that I don't feel is the actual intended default behaviour. admittedly these are edge cases.

**Comment by TarikHuber** [comment]
How I see it is like this:

@jswelsh update the state management how you planed to with reducing the number of variables. My sugesstion was only to use there the `useReducer`. If you think `useState` is enought you can try it with that.

In the config file is already a group for `marnu`, Just add there the default values for those states and if someone want's another behaviour he can change it there.
image

You can also use your own observables for the screen width but I'm not a fan of writing solutions for stuff that is already solved by others and Material-UI has a build in mediaQuery API just for such use cases: https://material-ui.com/components/use-media-query/#usemediaquery

**Comment by jswelsh** [comment]
@TarikHuber, thanks for the clarification, I think I understand now. The functions and hooks I added were just a short term solution before I figured out how I wanted to change the state variable. I realising now I'm better off just avoiding the adding complexity for a short term fix; I will instead only consolidate the state. I agree with using useReducer and will do that.

**Comment by TarikHuber** [comment]
@jswelsh how is it going? do you need help?

**Comment by jswelsh** [comment]
@TarikHuber. Had this on the backburner, I would appreciate some feedback.

What I was thinking was adding two files in the `src/providers/menu` 
 only refactoring `isDesktopOpen, isMobileOpen, useMiniMode, isMini`
replacing with an object 
```
menuStore = {
    miniMode: boolean
    menuOpen: boolean
    setMiniSwitchVisibility: boolean
  }
```
the files would be
```
//action.js
  const SET_MINI_MODE = 'SET_MINI_MODE'
  const SET_MENU_OPEN = 'SET_MENU_OPEN'
  const SET_MINI_SWITCH_VISIBILITY = 'SET_MINI_SWITCH_VISIBILITY' 

  const setMiniMode = (dispatch, payload) => dispatch({ type:SET_MINI_MODE, payload})
  const setMenuOpen = (dispatch, payload) => dispatch({ type:SET_MENU_OPEN, payload})
  const setMiniSwitchVisibility = (dispatch, payload) => dispatch({ type:SET_MINI_SWITCH_VISIBILITY, payload})
  
  export { setMiniMode,setMenuOpen, setMiniSwitchVisibility }
```

```
//state.js or store.js
  import { initialStateStuff } from './someWhere';


 import {
    SET_MINI_MODE,
    SET_MENU_OPEN,
    SET_MINI_SWITCH_VISIBILITY
  } from './actions'
  // use the initial state stuff
  const initializeState = {
    miniMode: useMediaQuery('(min-width:600px)'),
    menuOpen: true,
    setMiniSwitchVisibility: useMini
  }
  const reducer = (state, action) => {
    const { type, payload } = action

  switch (type) {
    case SET_MINI_MODE:
      return { ...state, miniMode: payload }
    case SET_MENU_OPEN:
      return { ...state, menuOpen: payload }
    case SET_MINI_SWITCH_VISIBILITY:
      return { ...state, setMiniSwitchVisibility: payload }
    default:
      return state
  }
}

export { reducer, initialState }
```
what is best for the project
1. state logic in a single reducer.js
2. keep everything in the providers.js
3. separate providers.js, store.js and action.js

**Comment by TarikHuber** [comment]
You can organize it like here in the Filter provider: https://github.com/TarikHuber/react-most-wanted/tree/master/packages/material-ui-shell/src/providers/Filter

Don't forget that you need to get the initialState from the configs by using the `appConfig`. There should by prop in the current Menu Provider in `material-ui-shell`.

**Comment by jswelsh** [comment]
@TarikHuber  is `rmw-shell-old` depreciated code thats not used with the other packages?

**Comment by TarikHuber** [comment]
Yup. I has it there to not forget migrating some stuff. Now all is migrated and we don't need it anymore.

**Comment by jswelsh** [comment]
Finished the basic state refactor. I mirrored the functionality from before. Unfortunately I had to choose between adding 

- a state property `mobileMenuOpen` and tracking the toggling  both desktop and mobile menu 'openness' 
- adding a hook to check when the view window is resized below 600px and forcing the menu closed ( requiring a very short debounce delay, else the user notices a slight delay on transition )
```
debounce(callback, ms) {
    let timer
    return () => {
      clearTimeout(timer)
      timer = setTimeout(() => {
        timer = null
        callback.apply(this, arguments)
      }, ms)
    }
  }
  useEffect(() => {
    const debouncedHandleResize = debounce(() => {
      console.log('yooooo')
      if(!issDesktop) {
        props.setMenuOpen(false)
        props.setMiniMode(false)
      }
    }, 50)
    window.addEventListener('resize', debouncedHandleResize)
    return () => {
      window.removeEventListener('resize', debouncedHandleResize)
    }
  }) 
```
I chose to maintain the original functionality and keeping two separate menu properties. I will add the hook that toggles the state as a config option as I do prefer this functionality over the default behaviour (specifically when you go from a mobile window size of ,600px to >600 and the menu just magically opens up). Will need to figure how to do that, as I don't think I've done something like this before. I will look at the codebase to get my bearings.

**Pull request closed without merging**
