### PR TITLE
fix for ImageUploadDialog in rmw-shell and added user profile editing page

### PR DESCRIPTION
**Pull request by UseMuse**
material ui shell - added user profile editing page.
Added an ImageUploadDialog container for specifying an avatar to a user, similar to rmw-shell, but without firebase. Added account deletion

### CODE REVIEW

**Comment by UseMuse** [comment]
I get duplicate ImageUploadDialog container in rmw-shell and in material-ui-shell, I think I need to use the ImageUploadDialog container from material-ui-shell to rmw-shell

**Comment by UseMuse** [comment]
further through this page it is planned to add enable / disable permission to receive notifications

**Review by UseMuse — COMMENTED** [review]
https://github.com/TarikHuber/react-most-wanted/issues/213

**Comment by TarikHuber** [comment]
why did you move MyAccount page to the template?

**Comment by UseMuse** [comment]
@TarikHuber of course

**Comment by UseMuse** [comment]
where does it belong?

**Comment by UseMuse** [comment]
@TarikHuber how to use the MyAccount page in the example if it is in material-ui-shell /src/pages/MyAccount ? add to config in pages?

**Pull request merged**
